version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=jpa-jee-architecture
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3307:3306'